# Generated by Django 3.0.5 on 2020-04-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_course_course_enrollment_peer_assessment_questions_team_team_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sem_of_realization',
            field=models.CharField(max_length=30),
        ),
    ]
