# Generated by Django 3.0.5 on 2020-04-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200416_2244'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('code', 'section_number', 'year', 'sem_of_realization'), name='unique_course'),
        ),
    ]
