# Generated by Django 3.0.5 on 2020-04-23 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200418_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AddField(
            model_name='team',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team_course', to='accounts.Course'),
        ),
        migrations.DeleteModel(
            name='Team_History',
        ),
        migrations.AddField(
            model_name='team_enrollment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='accounts.Team'),
        ),
        migrations.AddField(
            model_name='team_enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
