# Generated by Django 3.0.2 on 2020-04-23 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200423_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer_assessment',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Assessment_Completion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_name', to='accounts.Peer_Assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assessment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
