# Generated by Django 3.0.5 on 2020-04-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200423_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_completion',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='assessment_completion',
            name='grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment_completion',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peer_assessment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
