# Generated by Django 3.0.2 on 2020-04-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200425_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_enrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
