# Generated by Django 3.0.2 on 2020-04-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_team_enrollment_is_active'),
        ('accounts', '0009_auto_20200424_1536'),
    ]

    operations = [
    ]
