# Generated by Django 3.0.2 on 2020-04-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20200425_1143'),
        ('accounts', '0013_auto_20200425_1150'),
    ]

    operations = [
    ]
