# Generated by Django 3.0.2 on 2020-04-26 17:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20200426_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='student_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='peer_assessment',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 12, 20, 27, 972680)),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
