# Generated by Django 3.0.2 on 2020-04-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200426_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer_assessment',
            name='start_date',
            field=models.DateTimeField(default=''),
        ),
    ]
