# Generated by Django 3.0.2 on 2020-04-30 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200426_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='assessment_completion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='answer_completion', to='accounts.Assessment_Completion'),
        ),
        migrations.AddField(
            model_name='assessment_completion',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='completion_courses', to='accounts.Course'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('question', 'user', 'student', 'assessment_completion'), name='unique_answer'),
        ),
        migrations.AddConstraint(
            model_name='assessment_completion',
            constraint=models.UniqueConstraint(fields=('user', 'assessment', 'student', 'course'), name='unique_assessment_completion'),
        ),
    ]
